# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference for Standard Spring Boot properties is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

# spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring:
  application:
    name: airline-chat-bot
#  main:
#    banner-mode: off
#    web-application-type: none
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: logs/*,application.log,*.log,*.log.*
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      #      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      #      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration

  messages:
    basename: i18n/messages,i18n/errors,i18n/problems
    use-code-as-default-message: true
    #cache-duration=PT10S
    #fallback-to-system-locale=true
  jackson:
    serialization:
      write-dates-with-zone-id: true
      write-dates-as-timestamps: false
    #hateoas:
    #use-hal-as-default-json-media-type: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    problemdetails:
      enabled: false
  threads:
    virtual:
      enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
#    anthropic:
#      api-key: ${ANTHROPIC_API_KEY}
    mcp:
      client:
        name: ${spring.application.name}
        version: 0.0.1
        toolcallback.enabled: true
        sse.connections:
          rest-api-mcp-server:
            url: http://localhost:8080
        request-timeout: 5m

#------------------------- Swagger configuration -------------------------
#springdoc:
#  show-actuator: true
#  group-configs:
#    - group: actuator
#      display-name: Actuator
#      paths-to-match: /actuator/**
#    - group: airline
#      display-name: Airline
#      paths-to-match: /**
#      paths-to-exclude: /actuator/**

problem:
  type-url: http://localhost:${server.port}/problems/help.html
  debug-enabled: false
  stacktrace-enabled: false
  cause-chains-enabled: false

server:
  port: 8080
  forward-headers-strategy: framework
#    servlet:
#        context-path: /api

#------------------------- Actuators configuration -------------------------
# If not specified '/actuator' is taken as default. If specified must start with '/'
#management.endpoints.web.base-path=/
# Set it as "*", if you want to expose all actuator endpoints
management:
  endpoint:
    health:
      access: read_only
  endpoints:
    web:
      exposure:
        include: info,health,metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    console:
  level:
    ROOT: DEBUG
    '[org.springframework.ai]': debug
    '[io.modelcontextprotocol.client]': debug
    '[io.modelcontextprotocol.spec]': debug
debug: false

